apiVersion: v1
kind: ServiceAccount
metadata:
  name: flash-usdt-service-account
  namespace: flash-usdt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flash-usdt-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flash-usdt-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flash-usdt-cluster-role
subjects:
  - kind: ServiceAccount
    name: flash-usdt-service-account
    namespace: flash-usdt
